### ISSUE TITLE
Invalid display of option Less than or equal

### ISSUE THREAD

**Issue by dlipsy** [dlipsy/JibGridWpf#3]

**Comment by pareshjoshi** [comment]
Can you please add more details in the description? That will help contributors

**Comment by dlipsy** [comment]
> Can you please add more details in the description? That will help contributors

I will say I inherited the issues from: 
https://archive.codeplex.com/?p=jibgridwpf

I will likely be handling a few of these issues with a few pull requests, but I appreciate your input/help in addition to that. I'll post here once I've added my additional code to this.

**Comment by dlipsy** [comment]
Working on this issue in Issue-3 branch.
